[tool.poetry]
name = "hr-consultant"
version = "0.1.0"
description = "HR Consultant TG Bot"
authors = [
    "yourMasya <mmatvs@mail.ru>",
    "sashullel <klen.sasha_22@list.ru>"
]
readme = "README.md"
packages = [{include = "src", from = "."}]

[tool.poetry.dependencies]
python = "^3.12"
python-telegram-bot = "^22.4"
pdfplumber = "^0.11.7"
python-docx = "^1.2.0"
pydantic = "^2.12.4"
pydantic-settings = "^2.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
